package cn.cbdi.hunaninstrument.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cbdi.hunaninstrument.Bean.Keeper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KEEPER".
*/
public class KeeperDao extends AbstractDao<Keeper, String> {

    public static final String TABLENAME = "KEEPER";

    /**
     * Properties of entity Keeper.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CardID = new Property(0, String.class, "cardID", true, "CARD_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Headphoto = new Property(2, String.class, "headphoto", false, "HEADPHOTO");
        public final static Property HeadphotoRGB = new Property(3, String.class, "headphotoRGB", false, "HEADPHOTO_RGB");
        public final static Property HeadphotoBW = new Property(4, String.class, "headphotoBW", false, "HEADPHOTO_BW");
        public final static Property FaceUserId = new Property(5, String.class, "FaceUserId", false, "FACE_USER_ID");
        public final static Property Feature = new Property(6, byte[].class, "feature", false, "FEATURE");
    }


    public KeeperDao(DaoConfig config) {
        super(config);
    }
    
    public KeeperDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KEEPER\" (" + //
                "\"CARD_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: cardID
                "\"NAME\" TEXT," + // 1: name
                "\"HEADPHOTO\" TEXT," + // 2: headphoto
                "\"HEADPHOTO_RGB\" TEXT," + // 3: headphotoRGB
                "\"HEADPHOTO_BW\" TEXT," + // 4: headphotoBW
                "\"FACE_USER_ID\" TEXT," + // 5: FaceUserId
                "\"FEATURE\" BLOB);"); // 6: feature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KEEPER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Keeper entity) {
        stmt.clearBindings();
 
        String cardID = entity.getCardID();
        if (cardID != null) {
            stmt.bindString(1, cardID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String headphoto = entity.getHeadphoto();
        if (headphoto != null) {
            stmt.bindString(3, headphoto);
        }
 
        String headphotoRGB = entity.getHeadphotoRGB();
        if (headphotoRGB != null) {
            stmt.bindString(4, headphotoRGB);
        }
 
        String headphotoBW = entity.getHeadphotoBW();
        if (headphotoBW != null) {
            stmt.bindString(5, headphotoBW);
        }
 
        String FaceUserId = entity.getFaceUserId();
        if (FaceUserId != null) {
            stmt.bindString(6, FaceUserId);
        }
 
        byte[] feature = entity.getFeature();
        if (feature != null) {
            stmt.bindBlob(7, feature);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Keeper entity) {
        stmt.clearBindings();
 
        String cardID = entity.getCardID();
        if (cardID != null) {
            stmt.bindString(1, cardID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String headphoto = entity.getHeadphoto();
        if (headphoto != null) {
            stmt.bindString(3, headphoto);
        }
 
        String headphotoRGB = entity.getHeadphotoRGB();
        if (headphotoRGB != null) {
            stmt.bindString(4, headphotoRGB);
        }
 
        String headphotoBW = entity.getHeadphotoBW();
        if (headphotoBW != null) {
            stmt.bindString(5, headphotoBW);
        }
 
        String FaceUserId = entity.getFaceUserId();
        if (FaceUserId != null) {
            stmt.bindString(6, FaceUserId);
        }
 
        byte[] feature = entity.getFeature();
        if (feature != null) {
            stmt.bindBlob(7, feature);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Keeper readEntity(Cursor cursor, int offset) {
        Keeper entity = new Keeper( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // cardID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // headphoto
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // headphotoRGB
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // headphotoBW
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // FaceUserId
            cursor.isNull(offset + 6) ? null : cursor.getBlob(offset + 6) // feature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Keeper entity, int offset) {
        entity.setCardID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHeadphoto(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHeadphotoRGB(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHeadphotoBW(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFaceUserId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFeature(cursor.isNull(offset + 6) ? null : cursor.getBlob(offset + 6));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Keeper entity, long rowId) {
        return entity.getCardID();
    }
    
    @Override
    public String getKey(Keeper entity) {
        if(entity != null) {
            return entity.getCardID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Keeper entity) {
        return entity.getCardID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
